// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddServer(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string):Promise<main.ServerConnection>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CheckHealth(arg1:string):Promise<main.HealthStatus>;

export function CheckServer(arg1:string):Promise<main.ServerHealth>;

export function ClearClipboardHistory():Promise<void>;

export function ClipboardHistory():Promise<Array<main.ClipboardEntry>>;

export function ClosePullRequest(arg1:string,arg2:number):Promise<void>;

export function CloseServerTerminal(arg1:string):Promise<void>;

export function CommitChanges(arg1:string,arg2:string):Promise<void>;

export function CommitDiff(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CommitFiles(arg1:string,arg2:string):Promise<Array<main.CommitFile>>;

export function ComposeDown(arg1:string):Promise<void>;

export function Confirm(arg1:string,arg2:string):Promise<boolean>;

export function ContainerLogs(arg1:string):Promise<string>;

export function CountPullRequests(arg1:string,arg2:main.PullRequestFilter):Promise<main.PullRequestCounts>;

export function CreateBranch(arg1:string,arg2:string):Promise<void>;

export function CreatePullRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<main.PullRequest>;

export function CreateReviewComment(arg1:string,arg2:number,arg3:string,arg4:string,arg5:number,arg6:string,arg7:number,arg8:string,arg9:string):Promise<void>;

export function DeleteBranch(arg1:string,arg2:string):Promise<void>;

export function DeleteClipboardEntry(arg1:string):Promise<Array<main.ClipboardEntry>>;

export function DisableGitEvents(arg1:string):Promise<main.ActivitySummary>;

export function EnableGitEvents(arg1:string):Promise<main.ActivitySummary>;

export function ExportConfig(arg1:Array<string>):Promise<string>;

export function FetchRepo(arg1:string):Promise<void>;

export function FixServerKeyPermissions(arg1:string):Promise<void>;

export function GetActivity():Promise<main.ActivitySummary>;

export function GetAppVersion():Promise<string>;

export function GetNotificationSettings():Promise<main.NotificationSettings>;

export function GitChanges(arg1:string):Promise<Array<main.FileChange>>;

export function GitDiff(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function GitHubCLIInstalled():Promise<boolean>;

export function GitHubClientID():Promise<string>;

export function GitHubDevicePoll():Promise<string>;

export function GitHubDeviceStart():Promise<main.DeviceCode>;

export function GitHubLogout():Promise<void>;

export function GitHubSetToken(arg1:string):Promise<void>;

export function GitHubStatus(arg1:string):Promise<main.GitHubStatus>;

export function HealthHistory(arg1:string):Promise<Array<main.HealthSamplePoint>>;

export function IgnoreRepository(arg1:string):Promise<main.ActivitySummary>;

export function ImportConfig():Promise<main.ConfigBackup>;

export function InstallAndLoginGitHubCLI():Promise<void>;

export function InstalledApps():Promise<Array<main.InstalledApp>>;

export function IsFullscreen():Promise<boolean>;

export function KeyPermissionWarning(arg1:string):Promise<string>;

export function ListPullRequestAuthors(arg1:string):Promise<Array<string>>;

export function ListPullRequests(arg1:string,arg2:main.PullRequestFilter):Promise<Array<main.PullRequest>>;

export function ListRepositoryLabels(arg1:string):Promise<Array<string>>;

export function ListReviewComments(arg1:string,arg2:number):Promise<Array<main.ReviewComment>>;

export function ListServerContainers(arg1:string):Promise<Array<main.RemoteContainer>>;

export function ListServers():Promise<Array<main.ServerConnection>>;

export function MarkPullRequestReadyForReview(arg1:string,arg2:number):Promise<void>;

export function MergeBranch(arg1:string,arg2:string):Promise<void>;

export function MergePullRequest(arg1:string,arg2:number,arg3:string):Promise<void>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OpenContainerTerminal(arg1:string):Promise<void>;

export function OpenInstalledApp(arg1:string):Promise<void>;

export function OpenServerTerminal(arg1:string):Promise<string>;

export function PickFolder():Promise<string>;

export function PickKeyFile():Promise<string>;

export function ProcessLogs(arg1:number):Promise<string>;

export function ProjectLogs(arg1:string):Promise<string>;

export function PullRepo(arg1:string):Promise<void>;

export function PullRequestChecks(arg1:string,arg2:number):Promise<Array<main.CheckRun>>;

export function PullRequestCommits(arg1:string,arg2:number):Promise<Array<main.PullRequestCommit>>;

export function PullRequestDetail(arg1:string,arg2:number):Promise<main.PullRequestDetail>;

export function PullRequestFiles(arg1:string,arg2:number):Promise<Array<main.PullRequestFile>>;

export function PushRepo(arg1:string):Promise<void>;

export function QuitInstalledApp(arg1:string):Promise<void>;

export function RecentEvents(arg1:number):Promise<Array<main.TimelineEvent>>;

export function RecordClipboardCopy(arg1:string,arg2:string):Promise<Array<main.ClipboardEntry>>;

export function RefreshInstalledApps():Promise<Array<main.InstalledApp>>;

export function RefreshTools():Promise<main.ToolsSnapshot>;

export function RemoveServer(arg1:string):Promise<void>;

export function ReopenPullRequest(arg1:string,arg2:number):Promise<void>;

export function ReplyToReviewComment(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;

export function RepoBranches(arg1:string):Promise<Array<main.RepoBranch>>;

export function RepoCommits(arg1:string,arg2:number,arg3:number):Promise<Array<main.Commit>>;

export function RepoFile(arg1:string,arg2:string):Promise<string>;

export function RepoFiles(arg1:string,arg2:string):Promise<Array<main.RepoEntry>>;

export function RepoGraph(arg1:string,arg2:number):Promise<Array<main.GraphCommit>>;

export function RequestReviewers(arg1:string,arg2:number,arg3:Array<string>):Promise<void>;

export function ResizeServerTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveConflict(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResourceHistory(arg1:string):Promise<Array<main.ResourceSample>>;

export function Resources():Promise<main.ResourceSnapshot>;

export function RestartContainer(arg1:string):Promise<void>;

export function RestartServerContainer(arg1:string,arg2:string):Promise<void>;

export function ReviewPullRequest(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function RunServerCommand(arg1:string,arg2:string):Promise<string>;

export function RunToolAction(arg1:string,arg2:string):Promise<string>;

export function ServerContainerLogs(arg1:string,arg2:string):Promise<string>;

export function SetGitHubClientID(arg1:string):Promise<void>;

export function SetMineOnly(arg1:boolean):Promise<main.ActivitySummary>;

export function SetNotificationSettings(arg1:main.NotificationSettings):Promise<void>;

export function SetPullRequestLabels(arg1:string,arg2:number,arg3:Array<string>):Promise<void>;

export function Snapshot():Promise<main.Snapshot>;

export function StageFile(arg1:string,arg2:string):Promise<void>;

export function StartContainer(arg1:string):Promise<void>;

export function StartServerContainer(arg1:string,arg2:string):Promise<void>;

export function StashList(arg1:string):Promise<Array<string>>;

export function StashPop(arg1:string):Promise<void>;

export function StashSave(arg1:string):Promise<void>;

export function StopContainer(arg1:string):Promise<void>;

export function StopProcess(arg1:number):Promise<void>;

export function StopServerContainer(arg1:string,arg2:string):Promise<void>;

export function SwitchBranch(arg1:string,arg2:string):Promise<void>;

export function ToggleFullscreen():Promise<boolean>;

export function ToolActionStatus(arg1:string):Promise<main.ToolActionStatus>;

export function Tools():Promise<main.ToolsSnapshot>;

export function TrackRepository(arg1:string):Promise<main.ActivitySummary>;

export function UnstageFile(arg1:string,arg2:string):Promise<void>;

export function WriteServerTerminal(arg1:string,arg2:string):Promise<void>;
