// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {cron} from '../models';
import {security} from '../models';
import {context} from '../models';

export function ActivateContainerTerminal(arg1:string):Promise<void>;

export function AddAssignees(arg1:string,arg2:number,arg3:Array<string>):Promise<void>;

export function AddDocumentFolder(arg1:string):Promise<main.DocumentSnapshot>;

export function AddServer(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string,arg7:string):Promise<main.ServerConnection>;

export function AppendTerminalHistory(arg1:string,arg2:string):Promise<void>;

export function AskDocumentPassages(arg1:string,arg2:Array<main.DocumentSearchHit>):Promise<main.DocumentAnswer>;

export function AskDocuments(arg1:string):Promise<main.DocumentAnswer>;

export function CancelDocumentScan():Promise<boolean>;

export function CaptureOCR(arg1:string):Promise<string>;

export function CaptureThumbnail(arg1:string):Promise<string>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CheckHealth(arg1:string):Promise<main.HealthStatus>;

export function CheckServer(arg1:string):Promise<main.ServerHealth>;

export function CheckServerDraft(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<main.ServerHealth>;

export function CheckoutTag(arg1:string,arg2:string):Promise<void>;

export function ClearClipboardHistory():Promise<void>;

export function ClipboardHistory():Promise<Array<main.ClipboardEntry>>;

export function CloseContainerTerminal(arg1:string):Promise<void>;

export function ClosePullRequest(arg1:string,arg2:number):Promise<void>;

export function CloseServerTerminal(arg1:string):Promise<void>;

export function CommitChanges(arg1:string,arg2:string):Promise<void>;

export function CommitDiff(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CommitFiles(arg1:string,arg2:string):Promise<Array<main.CommitFile>>;

export function ComposeDown(arg1:string):Promise<void>;

export function Confirm(arg1:string,arg2:string):Promise<boolean>;

export function ConnectServerVPN(arg1:string):Promise<void>;

export function ContainerLogs(arg1:string):Promise<string>;

export function ContainerSize(arg1:string):Promise<string>;

export function CopyCaptureFile(arg1:string):Promise<void>;

export function CopyCaptureImage(arg1:string):Promise<void>;

export function CountPullRequests(arg1:string,arg2:main.PullRequestFilter):Promise<main.PullRequestCounts>;

export function CreateBranch(arg1:string,arg2:string):Promise<void>;

export function CreatePullRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<main.PullRequest>;

export function CreateReviewComment(arg1:string,arg2:number,arg3:string,arg4:string,arg5:number,arg6:string,arg7:number,arg8:string,arg9:string):Promise<void>;

export function CreateTag(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteBranch(arg1:string,arg2:string):Promise<void>;

export function DeleteCapture(arg1:string):Promise<main.CapturesSnapshot>;

export function DeleteClipboardEntry(arg1:string):Promise<Array<main.ClipboardEntry>>;

export function DeleteInstalledApp(arg1:string):Promise<void>;

export function DeleteRemoteTag(arg1:string,arg2:string):Promise<void>;

export function DeleteTag(arg1:string,arg2:string):Promise<void>;

export function DeleteWorkspaceProfile(arg1:string):Promise<main.ProductPreferences>;

export function DisableGitEvents(arg1:string):Promise<main.ActivitySummary>;

export function DisconnectServerVPN(arg1:string):Promise<void>;

export function DocumentLibrary():Promise<main.DocumentSnapshot>;

export function DocumentPlainText(arg1:string):Promise<string>;

export function DownloadServerFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function EditCapture(arg1:string):Promise<void>;

export function EnableGitEvents(arg1:string):Promise<main.ActivitySummary>;

export function ExcludeDocument(arg1:string):Promise<main.DocumentSnapshot>;

export function ExportConfig(arg1:Array<string>,arg2:Record<string, string>):Promise<string>;

export function FetchRepo(arg1:string):Promise<void>;

export function FixServerKeyPermissions(arg1:string):Promise<void>;

export function GetActivity(arg1:boolean):Promise<main.ActivitySummary>;

export function GetAppVersion():Promise<string>;

export function GetClipboardHistoryEnabled():Promise<boolean>;

export function GetContainerRuntimeStatus():Promise<main.ContainerRuntimeStatus>;

export function GetEnvFileContent(arg1:string,arg2:string):Promise<string>;

export function GetEnvValue(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetGitHookStatus(arg1:string):Promise<main.GitHookStatus>;

export function GetNotificationSettings():Promise<main.NotificationSettings>;

export function GetTerminalHistory(arg1:string):Promise<Array<string>>;

export function GitChanges(arg1:string):Promise<Array<main.FileChange>>;

export function GitDiff(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function GitHubCLIAccounts():Promise<Array<main.GitHubCLIAccount>>;

export function GitHubCLIInstalled():Promise<boolean>;

export function GitHubClientID():Promise<string>;

export function GitHubDevicePoll():Promise<string>;

export function GitHubDeviceStart():Promise<main.DeviceCode>;

export function GitHubLogout():Promise<void>;

export function GitHubSetToken(arg1:string):Promise<void>;

export function GitHubStatus(arg1:string):Promise<main.GitHubStatus>;

export function HasVSCode():Promise<boolean>;

export function HealthHistory(arg1:string):Promise<Array<main.HealthSamplePoint>>;

export function IgnoreRepository(arg1:string):Promise<main.ActivitySummary>;

export function ImportConfig():Promise<main.ConfigBackup>;

export function InstallAndLoginGitHubCLI():Promise<void>;

export function InstallBrewPackage(arg1:string,arg2:boolean):Promise<string>;

export function InstallColima():Promise<void>;

export function InstallGitHook(arg1:string,arg2:string):Promise<void>;

export function InstallLanguagePackage(arg1:string,arg2:string):Promise<string>;

export function InstalledApps():Promise<Array<main.InstalledApp>>;

export function IsFullscreen():Promise<boolean>;

export function KeyPermissionWarning(arg1:string):Promise<string>;

export function ListBrewPackages():Promise<main.BrewPackages>;

export function ListCaptures():Promise<main.CapturesSnapshot>;

export function ListConfigFiles():Promise<Array<main.ConfigFileEntry>>;

export function ListEnvFiles():Promise<Array<main.EnvFileSummary>>;

export function ListLanguagePackages(arg1:string):Promise<Array<string>>;

export function ListPullRequestAuthors(arg1:string):Promise<Array<string>>;

export function ListPullRequests(arg1:string,arg2:main.PullRequestFilter):Promise<Array<main.PullRequest>>;

export function ListRepositoryCollaborators(arg1:string):Promise<Array<string>>;

export function ListRepositoryLabels(arg1:string):Promise<Array<string>>;

export function ListReviewComments(arg1:string,arg2:number):Promise<Array<main.ReviewComment>>;

export function ListSSHConfigHosts():Promise<Array<main.SSHConfigHost>>;

export function ListServerContainers(arg1:string):Promise<Array<main.RemoteContainer>>;

export function ListServerCron(arg1:string):Promise<Array<cron.Job>>;

export function ListServerFiles(arg1:string,arg2:string):Promise<Array<main.RemoteFile>>;

export function ListServers():Promise<Array<main.ServerConnection>>;

export function ListVPNEngines():Promise<Array<main.VPNEngineInfo>>;

export function LoadCaptureImage(arg1:string):Promise<string>;

export function MarkPullRequestReadyForReview(arg1:string,arg2:number):Promise<void>;

export function MergeBranch(arg1:string,arg2:string):Promise<void>;

export function MergePullRequest(arg1:string,arg2:number,arg3:string):Promise<void>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OpenCapture(arg1:string):Promise<void>;

export function OpenContainerTerminal(arg1:string):Promise<string>;

export function OpenDocument(arg1:string):Promise<void>;

export function OpenFileAtLine(arg1:string,arg2:string,arg3:number):Promise<void>;

export function OpenHomebrewInstallInTerminal():Promise<void>;

export function OpenInstalledApp(arg1:string):Promise<void>;

export function OpenPathInFinder(arg1:string):Promise<void>;

export function OpenServerTerminal(arg1:string):Promise<string>;

export function OpenSystemVPNSettings():Promise<void>;

export function PerformSelfUpdate(arg1:string):Promise<void>;

export function PickCaptureFolder():Promise<string>;

export function PickDocumentFolder():Promise<string>;

export function PickDownloadFolder():Promise<string>;

export function PickFolder():Promise<string>;

export function PickKeyFile():Promise<string>;

export function PickUploadFile():Promise<string>;

export function PreviewDocument(arg1:string):Promise<void>;

export function ProcessLogs(arg1:number):Promise<string>;

export function ProductPreferences():Promise<main.ProductPreferences>;

export function ProjectLogs(arg1:string):Promise<string>;

export function PullRepo(arg1:string):Promise<void>;

export function PullRequestChecks(arg1:string,arg2:number):Promise<Array<main.CheckRun>>;

export function PullRequestCommits(arg1:string,arg2:number):Promise<Array<main.PullRequestCommit>>;

export function PullRequestDetail(arg1:string,arg2:number):Promise<main.PullRequestDetail>;

export function PullRequestFiles(arg1:string,arg2:number):Promise<Array<main.PullRequestFile>>;

export function PushBranch(arg1:string,arg2:string):Promise<void>;

export function PushRepo(arg1:string):Promise<void>;

export function PushTag(arg1:string,arg2:string):Promise<void>;

export function QuitInstalledApp(arg1:string):Promise<void>;

export function RecentEvents(arg1:number):Promise<Array<main.TimelineEvent>>;

export function RecordClipboardCopy(arg1:string,arg2:string):Promise<Array<main.ClipboardEntry>>;

export function RefreshDocuments():Promise<main.DocumentSnapshot>;

export function RefreshInstalledApps():Promise<Array<main.InstalledApp>>;

export function RefreshTools():Promise<main.ToolsSnapshot>;

export function RemoveAssignees(arg1:string,arg2:number,arg3:Array<string>):Promise<void>;

export function RemoveDocumentFolder(arg1:string):Promise<main.DocumentSnapshot>;

export function RemoveReviewers(arg1:string,arg2:number,arg3:Array<string>):Promise<void>;

export function RemoveServer(arg1:string):Promise<void>;

export function RemoveServerCronLine(arg1:string,arg2:number):Promise<void>;

export function RemoveServerVPNConfig(arg1:string):Promise<void>;

export function RenameCapture(arg1:string,arg2:string):Promise<main.CapturesSnapshot>;

export function RenameDocumentFolder(arg1:string,arg2:string):Promise<main.DocumentSnapshot>;

export function ReopenPullRequest(arg1:string,arg2:number):Promise<void>;

export function ReplyToReviewComment(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;

export function RepoBranches(arg1:string):Promise<Array<main.RepoBranch>>;

export function RepoCommits(arg1:string,arg2:number,arg3:number):Promise<Array<main.Commit>>;

export function RepoFile(arg1:string,arg2:string):Promise<string>;

export function RepoFiles(arg1:string,arg2:string):Promise<Array<main.RepoEntry>>;

export function RepoGitHubOwner(arg1:string):Promise<string>;

export function RepoGraph(arg1:string,arg2:number):Promise<Array<main.GraphCommit>>;

export function RepoTags(arg1:string):Promise<Array<main.RepoTag>>;

export function RequestReviewers(arg1:string,arg2:number,arg3:Array<string>):Promise<void>;

export function ResizeContainerTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResizeServerTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveConflict(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResourceHistory(arg1:string):Promise<Array<main.ResourceSample>>;

export function Resources():Promise<main.ResourceSnapshot>;

export function RestartContainer(arg1:string):Promise<void>;

export function RestartServerContainer(arg1:string,arg2:string):Promise<void>;

export function RestoreExcludedDocument(arg1:string):Promise<main.DocumentSnapshot>;

export function RevealCapture(arg1:string):Promise<void>;

export function RevealDocument(arg1:string):Promise<void>;

export function RevealFileInFinder(arg1:string,arg2:string):Promise<void>;

export function ReviewPullRequest(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function RunSecurityScan(arg1:string):Promise<security.Report>;

export function RunSecurityScanAll(arg1:Array<string>):Promise<Array<security.Report>>;

export function RunServerCommand(arg1:string,arg2:string):Promise<string>;

export function RunToolAction(arg1:string,arg2:string):Promise<string>;

export function SaveEditedCapture(arg1:string,arg2:string):Promise<main.CapturesSnapshot>;

export function SaveEditedCaptureAs(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveWorkspaceProfile(arg1:main.WorkspaceProfile):Promise<main.ProductPreferences>;

export function ScanContainerImage(arg1:string):Promise<security.Report>;

export function SearchBrewPackages(arg1:string):Promise<Array<main.BrewSearchResult>>;

export function SearchDocuments(arg1:string):Promise<Array<main.DocumentSearchHit>>;

export function SearchLanguagePackages(arg1:string,arg2:string):Promise<Array<main.RegistryPackage>>;

export function SemanticSearchDocuments(arg1:string):Promise<Array<main.DocumentSearchHit>>;

export function ServerContainerLogs(arg1:string,arg2:string):Promise<string>;

export function ServerVPNStatus(arg1:string):Promise<main.VPNStatus>;

export function SetCaptureFolder(arg1:string):Promise<main.CapturesSnapshot>;

export function SetClipboardHistoryEnabled(arg1:boolean):Promise<void>;

export function SetDocumentRootPolicy(arg1:string,arg2:main.DocumentRootPolicy):Promise<main.ProductPreferences>;

export function SetGitHubClientID(arg1:string):Promise<void>;

export function SetMineOnly(arg1:boolean):Promise<main.ActivitySummary>;

export function SetNotificationSettings(arg1:main.NotificationSettings):Promise<void>;

export function SetProjectExpectedState(arg1:string,arg2:string):Promise<main.ProductPreferences>;

export function SetPullRequestLabels(arg1:string,arg2:number,arg3:Array<string>):Promise<void>;

export function SetServerCronEnabled(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function SetServerVPNConfig(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function Snapshot(arg1:boolean):Promise<main.Snapshot>;

export function StageFile(arg1:string,arg2:string):Promise<void>;

export function StartContainer(arg1:string):Promise<void>;

export function StartContainerRuntime(arg1:string):Promise<void>;

export function StartServerContainer(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StashList(arg1:string):Promise<Array<string>>;

export function StashPop(arg1:string):Promise<void>;

export function StashSave(arg1:string):Promise<void>;

export function StopContainer(arg1:string):Promise<void>;

export function StopContainerRuntime(arg1:string):Promise<void>;

export function StopProcess(arg1:number):Promise<void>;

export function StopServerContainer(arg1:string,arg2:string):Promise<void>;

export function SwitchBranch(arg1:string,arg2:string):Promise<void>;

export function SwitchGitHubCLIAccount(arg1:string):Promise<void>;

export function ToggleConfigFile(arg1:string):Promise<boolean>;

export function ToggleFullscreen():Promise<boolean>;

export function ToggleTelemetry():Promise<boolean>;

export function ToolActionStatus(arg1:string):Promise<main.ToolActionStatus>;

export function Tools():Promise<main.ToolsSnapshot>;

export function TrackRepository(arg1:string):Promise<main.ActivitySummary>;

export function UninstallBrewPackage(arg1:string,arg2:boolean):Promise<string>;

export function UninstallGitHook(arg1:string,arg2:string):Promise<void>;

export function UninstallLanguagePackage(arg1:string,arg2:string):Promise<string>;

export function UnstageFile(arg1:string,arg2:string):Promise<void>;

export function UpdateServer(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string,arg7:string,arg8:string):Promise<main.ServerConnection>;

export function UploadServerFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UseDedicatedCaptureFolder(arg1:boolean):Promise<main.CapturesSnapshot>;

export function WriteContainerTerminal(arg1:string,arg2:string):Promise<void>;

export function WriteServerTerminal(arg1:string,arg2:string):Promise<void>;
