// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateContainerTerminal(arg1) {
  return window['go']['main']['App']['ActivateContainerTerminal'](arg1);
}

export function AddAssignees(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddAssignees'](arg1, arg2, arg3);
}

export function AddDocumentFolder(arg1) {
  return window['go']['main']['App']['AddDocumentFolder'](arg1);
}

export function AddServer(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddServer'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AppendTerminalHistory(arg1, arg2) {
  return window['go']['main']['App']['AppendTerminalHistory'](arg1, arg2);
}

export function AskDocuments(arg1) {
  return window['go']['main']['App']['AskDocuments'](arg1);
}

export function CancelDocumentScan() {
  return window['go']['main']['App']['CancelDocumentScan']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckHealth(arg1) {
  return window['go']['main']['App']['CheckHealth'](arg1);
}

export function CheckServer(arg1) {
  return window['go']['main']['App']['CheckServer'](arg1);
}

export function CheckServerDraft(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CheckServerDraft'](arg1, arg2, arg3, arg4, arg5);
}

export function ClearClipboardHistory() {
  return window['go']['main']['App']['ClearClipboardHistory']();
}

export function ClipboardHistory() {
  return window['go']['main']['App']['ClipboardHistory']();
}

export function CloseContainerTerminal(arg1) {
  return window['go']['main']['App']['CloseContainerTerminal'](arg1);
}

export function ClosePullRequest(arg1, arg2) {
  return window['go']['main']['App']['ClosePullRequest'](arg1, arg2);
}

export function CloseServerTerminal(arg1) {
  return window['go']['main']['App']['CloseServerTerminal'](arg1);
}

export function CommitChanges(arg1, arg2) {
  return window['go']['main']['App']['CommitChanges'](arg1, arg2);
}

export function CommitDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['CommitDiff'](arg1, arg2, arg3);
}

export function CommitFiles(arg1, arg2) {
  return window['go']['main']['App']['CommitFiles'](arg1, arg2);
}

export function ComposeDown(arg1) {
  return window['go']['main']['App']['ComposeDown'](arg1);
}

export function Confirm(arg1, arg2) {
  return window['go']['main']['App']['Confirm'](arg1, arg2);
}

export function ConnectServerVPN(arg1) {
  return window['go']['main']['App']['ConnectServerVPN'](arg1);
}

export function ContainerLogs(arg1) {
  return window['go']['main']['App']['ContainerLogs'](arg1);
}

export function CountPullRequests(arg1, arg2) {
  return window['go']['main']['App']['CountPullRequests'](arg1, arg2);
}

export function CreateBranch(arg1, arg2) {
  return window['go']['main']['App']['CreateBranch'](arg1, arg2);
}

export function CreatePullRequest(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreatePullRequest'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateReviewComment(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['CreateReviewComment'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function DeleteBranch(arg1, arg2) {
  return window['go']['main']['App']['DeleteBranch'](arg1, arg2);
}

export function DeleteClipboardEntry(arg1) {
  return window['go']['main']['App']['DeleteClipboardEntry'](arg1);
}

export function DeleteInstalledApp(arg1) {
  return window['go']['main']['App']['DeleteInstalledApp'](arg1);
}

export function DisableGitEvents(arg1) {
  return window['go']['main']['App']['DisableGitEvents'](arg1);
}

export function DisconnectServerVPN(arg1) {
  return window['go']['main']['App']['DisconnectServerVPN'](arg1);
}

export function DocumentLibrary() {
  return window['go']['main']['App']['DocumentLibrary']();
}

export function DownloadServerFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadServerFile'](arg1, arg2, arg3);
}

export function EnableGitEvents(arg1) {
  return window['go']['main']['App']['EnableGitEvents'](arg1);
}

export function ExportConfig(arg1) {
  return window['go']['main']['App']['ExportConfig'](arg1);
}

export function FetchRepo(arg1) {
  return window['go']['main']['App']['FetchRepo'](arg1);
}

export function FixServerKeyPermissions(arg1) {
  return window['go']['main']['App']['FixServerKeyPermissions'](arg1);
}

export function GetActivity(arg1) {
  return window['go']['main']['App']['GetActivity'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetClipboardHistoryEnabled() {
  return window['go']['main']['App']['GetClipboardHistoryEnabled']();
}

export function GetContainerRuntimeStatus() {
  return window['go']['main']['App']['GetContainerRuntimeStatus']();
}

export function GetEnvFileContent(arg1, arg2) {
  return window['go']['main']['App']['GetEnvFileContent'](arg1, arg2);
}

export function GetEnvValue(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetEnvValue'](arg1, arg2, arg3);
}

export function GetGitHookStatus(arg1) {
  return window['go']['main']['App']['GetGitHookStatus'](arg1);
}

export function GetNotificationSettings() {
  return window['go']['main']['App']['GetNotificationSettings']();
}

export function GetTerminalHistory(arg1) {
  return window['go']['main']['App']['GetTerminalHistory'](arg1);
}

export function GitChanges(arg1) {
  return window['go']['main']['App']['GitChanges'](arg1);
}

export function GitDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitDiff'](arg1, arg2, arg3);
}

export function GitHubCLIAccounts() {
  return window['go']['main']['App']['GitHubCLIAccounts']();
}

export function GitHubCLIInstalled() {
  return window['go']['main']['App']['GitHubCLIInstalled']();
}

export function GitHubClientID() {
  return window['go']['main']['App']['GitHubClientID']();
}

export function GitHubDevicePoll() {
  return window['go']['main']['App']['GitHubDevicePoll']();
}

export function GitHubDeviceStart() {
  return window['go']['main']['App']['GitHubDeviceStart']();
}

export function GitHubLogout() {
  return window['go']['main']['App']['GitHubLogout']();
}

export function GitHubSetToken(arg1) {
  return window['go']['main']['App']['GitHubSetToken'](arg1);
}

export function GitHubStatus(arg1) {
  return window['go']['main']['App']['GitHubStatus'](arg1);
}

export function HasVSCode() {
  return window['go']['main']['App']['HasVSCode']();
}

export function HealthHistory(arg1) {
  return window['go']['main']['App']['HealthHistory'](arg1);
}

export function IgnoreRepository(arg1) {
  return window['go']['main']['App']['IgnoreRepository'](arg1);
}

export function ImportConfig() {
  return window['go']['main']['App']['ImportConfig']();
}

export function InstallAndLoginGitHubCLI() {
  return window['go']['main']['App']['InstallAndLoginGitHubCLI']();
}

export function InstallBrewPackage(arg1, arg2) {
  return window['go']['main']['App']['InstallBrewPackage'](arg1, arg2);
}

export function InstallColima() {
  return window['go']['main']['App']['InstallColima']();
}

export function InstallGitHook(arg1, arg2) {
  return window['go']['main']['App']['InstallGitHook'](arg1, arg2);
}

export function InstallLanguagePackage(arg1, arg2) {
  return window['go']['main']['App']['InstallLanguagePackage'](arg1, arg2);
}

export function InstalledApps() {
  return window['go']['main']['App']['InstalledApps']();
}

export function IsFullscreen() {
  return window['go']['main']['App']['IsFullscreen']();
}

export function KeyPermissionWarning(arg1) {
  return window['go']['main']['App']['KeyPermissionWarning'](arg1);
}

export function ListBrewPackages() {
  return window['go']['main']['App']['ListBrewPackages']();
}

export function ListConfigFiles() {
  return window['go']['main']['App']['ListConfigFiles']();
}

export function ListEnvFiles() {
  return window['go']['main']['App']['ListEnvFiles']();
}

export function ListLanguagePackages(arg1) {
  return window['go']['main']['App']['ListLanguagePackages'](arg1);
}

export function ListPullRequestAuthors(arg1) {
  return window['go']['main']['App']['ListPullRequestAuthors'](arg1);
}

export function ListPullRequests(arg1, arg2) {
  return window['go']['main']['App']['ListPullRequests'](arg1, arg2);
}

export function ListRepositoryCollaborators(arg1) {
  return window['go']['main']['App']['ListRepositoryCollaborators'](arg1);
}

export function ListRepositoryLabels(arg1) {
  return window['go']['main']['App']['ListRepositoryLabels'](arg1);
}

export function ListReviewComments(arg1, arg2) {
  return window['go']['main']['App']['ListReviewComments'](arg1, arg2);
}

export function ListSSHConfigHosts() {
  return window['go']['main']['App']['ListSSHConfigHosts']();
}

export function ListServerContainers(arg1) {
  return window['go']['main']['App']['ListServerContainers'](arg1);
}

export function ListServerCron(arg1) {
  return window['go']['main']['App']['ListServerCron'](arg1);
}

export function ListServerFiles(arg1, arg2) {
  return window['go']['main']['App']['ListServerFiles'](arg1, arg2);
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function ListVPNEngines() {
  return window['go']['main']['App']['ListVPNEngines']();
}

export function MarkPullRequestReadyForReview(arg1, arg2) {
  return window['go']['main']['App']['MarkPullRequestReadyForReview'](arg1, arg2);
}

export function MergeBranch(arg1, arg2) {
  return window['go']['main']['App']['MergeBranch'](arg1, arg2);
}

export function MergePullRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['MergePullRequest'](arg1, arg2, arg3);
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function OpenContainerTerminal(arg1) {
  return window['go']['main']['App']['OpenContainerTerminal'](arg1);
}

export function OpenDocument(arg1) {
  return window['go']['main']['App']['OpenDocument'](arg1);
}

export function OpenFileAtLine(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenFileAtLine'](arg1, arg2, arg3);
}

export function OpenHomebrewInstallInTerminal() {
  return window['go']['main']['App']['OpenHomebrewInstallInTerminal']();
}

export function OpenInstalledApp(arg1) {
  return window['go']['main']['App']['OpenInstalledApp'](arg1);
}

export function OpenPathInFinder(arg1) {
  return window['go']['main']['App']['OpenPathInFinder'](arg1);
}

export function OpenServerTerminal(arg1) {
  return window['go']['main']['App']['OpenServerTerminal'](arg1);
}

export function OpenSystemVPNSettings() {
  return window['go']['main']['App']['OpenSystemVPNSettings']();
}

export function PerformSelfUpdate(arg1) {
  return window['go']['main']['App']['PerformSelfUpdate'](arg1);
}

export function PickDocumentFolder() {
  return window['go']['main']['App']['PickDocumentFolder']();
}

export function PickDownloadFolder() {
  return window['go']['main']['App']['PickDownloadFolder']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PickKeyFile() {
  return window['go']['main']['App']['PickKeyFile']();
}

export function PickUploadFile() {
  return window['go']['main']['App']['PickUploadFile']();
}

export function ProcessLogs(arg1) {
  return window['go']['main']['App']['ProcessLogs'](arg1);
}

export function ProjectLogs(arg1) {
  return window['go']['main']['App']['ProjectLogs'](arg1);
}

export function PullRepo(arg1) {
  return window['go']['main']['App']['PullRepo'](arg1);
}

export function PullRequestChecks(arg1, arg2) {
  return window['go']['main']['App']['PullRequestChecks'](arg1, arg2);
}

export function PullRequestCommits(arg1, arg2) {
  return window['go']['main']['App']['PullRequestCommits'](arg1, arg2);
}

export function PullRequestDetail(arg1, arg2) {
  return window['go']['main']['App']['PullRequestDetail'](arg1, arg2);
}

export function PullRequestFiles(arg1, arg2) {
  return window['go']['main']['App']['PullRequestFiles'](arg1, arg2);
}

export function PushBranch(arg1, arg2) {
  return window['go']['main']['App']['PushBranch'](arg1, arg2);
}

export function PushRepo(arg1) {
  return window['go']['main']['App']['PushRepo'](arg1);
}

export function QuitInstalledApp(arg1) {
  return window['go']['main']['App']['QuitInstalledApp'](arg1);
}

export function RecentEvents(arg1) {
  return window['go']['main']['App']['RecentEvents'](arg1);
}

export function RecordClipboardCopy(arg1, arg2) {
  return window['go']['main']['App']['RecordClipboardCopy'](arg1, arg2);
}

export function RefreshDocuments() {
  return window['go']['main']['App']['RefreshDocuments']();
}

export function RefreshInstalledApps() {
  return window['go']['main']['App']['RefreshInstalledApps']();
}

export function RefreshTools() {
  return window['go']['main']['App']['RefreshTools']();
}

export function RemoveAssignees(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveAssignees'](arg1, arg2, arg3);
}

export function RemoveDocumentFolder(arg1) {
  return window['go']['main']['App']['RemoveDocumentFolder'](arg1);
}

export function RemoveReviewers(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveReviewers'](arg1, arg2, arg3);
}

export function RemoveServer(arg1) {
  return window['go']['main']['App']['RemoveServer'](arg1);
}

export function RemoveServerCronLine(arg1, arg2) {
  return window['go']['main']['App']['RemoveServerCronLine'](arg1, arg2);
}

export function RemoveServerVPNConfig(arg1) {
  return window['go']['main']['App']['RemoveServerVPNConfig'](arg1);
}

export function ReopenPullRequest(arg1, arg2) {
  return window['go']['main']['App']['ReopenPullRequest'](arg1, arg2);
}

export function ReplyToReviewComment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReplyToReviewComment'](arg1, arg2, arg3, arg4);
}

export function RepoBranches(arg1) {
  return window['go']['main']['App']['RepoBranches'](arg1);
}

export function RepoCommits(arg1, arg2, arg3) {
  return window['go']['main']['App']['RepoCommits'](arg1, arg2, arg3);
}

export function RepoFile(arg1, arg2) {
  return window['go']['main']['App']['RepoFile'](arg1, arg2);
}

export function RepoFiles(arg1, arg2) {
  return window['go']['main']['App']['RepoFiles'](arg1, arg2);
}

export function RepoGitHubOwner(arg1) {
  return window['go']['main']['App']['RepoGitHubOwner'](arg1);
}

export function RepoGraph(arg1, arg2) {
  return window['go']['main']['App']['RepoGraph'](arg1, arg2);
}

export function RequestReviewers(arg1, arg2, arg3) {
  return window['go']['main']['App']['RequestReviewers'](arg1, arg2, arg3);
}

export function ResizeContainerTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeContainerTerminal'](arg1, arg2, arg3);
}

export function ResizeServerTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeServerTerminal'](arg1, arg2, arg3);
}

export function ResolveConflict(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveConflict'](arg1, arg2, arg3);
}

export function ResourceHistory(arg1) {
  return window['go']['main']['App']['ResourceHistory'](arg1);
}

export function Resources() {
  return window['go']['main']['App']['Resources']();
}

export function RestartContainer(arg1) {
  return window['go']['main']['App']['RestartContainer'](arg1);
}

export function RestartServerContainer(arg1, arg2) {
  return window['go']['main']['App']['RestartServerContainer'](arg1, arg2);
}

export function RevealDocument(arg1) {
  return window['go']['main']['App']['RevealDocument'](arg1);
}

export function RevealFileInFinder(arg1, arg2) {
  return window['go']['main']['App']['RevealFileInFinder'](arg1, arg2);
}

export function ReviewPullRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReviewPullRequest'](arg1, arg2, arg3, arg4);
}

export function RunSecurityScan(arg1) {
  return window['go']['main']['App']['RunSecurityScan'](arg1);
}

export function RunSecurityScanAll(arg1) {
  return window['go']['main']['App']['RunSecurityScanAll'](arg1);
}

export function RunServerCommand(arg1, arg2) {
  return window['go']['main']['App']['RunServerCommand'](arg1, arg2);
}

export function RunToolAction(arg1, arg2) {
  return window['go']['main']['App']['RunToolAction'](arg1, arg2);
}

export function ScanContainerImage(arg1) {
  return window['go']['main']['App']['ScanContainerImage'](arg1);
}

export function SearchBrewPackages(arg1) {
  return window['go']['main']['App']['SearchBrewPackages'](arg1);
}

export function SearchDocuments(arg1) {
  return window['go']['main']['App']['SearchDocuments'](arg1);
}

export function SearchLanguagePackages(arg1, arg2) {
  return window['go']['main']['App']['SearchLanguagePackages'](arg1, arg2);
}

export function ServerContainerLogs(arg1, arg2) {
  return window['go']['main']['App']['ServerContainerLogs'](arg1, arg2);
}

export function ServerVPNStatus(arg1) {
  return window['go']['main']['App']['ServerVPNStatus'](arg1);
}

export function SetClipboardHistoryEnabled(arg1) {
  return window['go']['main']['App']['SetClipboardHistoryEnabled'](arg1);
}

export function SetGitHubClientID(arg1) {
  return window['go']['main']['App']['SetGitHubClientID'](arg1);
}

export function SetMineOnly(arg1) {
  return window['go']['main']['App']['SetMineOnly'](arg1);
}

export function SetNotificationSettings(arg1) {
  return window['go']['main']['App']['SetNotificationSettings'](arg1);
}

export function SetPullRequestLabels(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPullRequestLabels'](arg1, arg2, arg3);
}

export function SetServerCronEnabled(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetServerCronEnabled'](arg1, arg2, arg3);
}

export function SetServerVPNConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetServerVPNConfig'](arg1, arg2, arg3);
}

export function Snapshot(arg1) {
  return window['go']['main']['App']['Snapshot'](arg1);
}

export function StageFile(arg1, arg2) {
  return window['go']['main']['App']['StageFile'](arg1, arg2);
}

export function StartContainer(arg1) {
  return window['go']['main']['App']['StartContainer'](arg1);
}

export function StartContainerRuntime(arg1) {
  return window['go']['main']['App']['StartContainerRuntime'](arg1);
}

export function StartServerContainer(arg1, arg2) {
  return window['go']['main']['App']['StartServerContainer'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function StashList(arg1) {
  return window['go']['main']['App']['StashList'](arg1);
}

export function StashPop(arg1) {
  return window['go']['main']['App']['StashPop'](arg1);
}

export function StashSave(arg1) {
  return window['go']['main']['App']['StashSave'](arg1);
}

export function StopContainer(arg1) {
  return window['go']['main']['App']['StopContainer'](arg1);
}

export function StopContainerRuntime(arg1) {
  return window['go']['main']['App']['StopContainerRuntime'](arg1);
}

export function StopProcess(arg1) {
  return window['go']['main']['App']['StopProcess'](arg1);
}

export function StopServerContainer(arg1, arg2) {
  return window['go']['main']['App']['StopServerContainer'](arg1, arg2);
}

export function SwitchBranch(arg1, arg2) {
  return window['go']['main']['App']['SwitchBranch'](arg1, arg2);
}

export function SwitchGitHubCLIAccount(arg1) {
  return window['go']['main']['App']['SwitchGitHubCLIAccount'](arg1);
}

export function ToggleConfigFile(arg1) {
  return window['go']['main']['App']['ToggleConfigFile'](arg1);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function ToggleTelemetry() {
  return window['go']['main']['App']['ToggleTelemetry']();
}

export function ToolActionStatus(arg1) {
  return window['go']['main']['App']['ToolActionStatus'](arg1);
}

export function Tools() {
  return window['go']['main']['App']['Tools']();
}

export function TrackRepository(arg1) {
  return window['go']['main']['App']['TrackRepository'](arg1);
}

export function UninstallBrewPackage(arg1, arg2) {
  return window['go']['main']['App']['UninstallBrewPackage'](arg1, arg2);
}

export function UninstallGitHook(arg1, arg2) {
  return window['go']['main']['App']['UninstallGitHook'](arg1, arg2);
}

export function UninstallLanguagePackage(arg1, arg2) {
  return window['go']['main']['App']['UninstallLanguagePackage'](arg1, arg2);
}

export function UnstageFile(arg1, arg2) {
  return window['go']['main']['App']['UnstageFile'](arg1, arg2);
}

export function UpdateServer(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateServer'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UploadServerFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadServerFile'](arg1, arg2, arg3);
}

export function WriteContainerTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteContainerTerminal'](arg1, arg2);
}

export function WriteServerTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteServerTerminal'](arg1, arg2);
}
